# Generated by Django 5.2 on 2025-04-23 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteattachment',
            name='file_size',
        ),
    ]
