# Generated by Django 5.2 on 2025-04-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_remove_quoteattachment_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteattachment',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
